# today

basically reading documentation

from the [pytest docs on pytest.raises](https://docs.pytest.org/en/6.2.x/reference.html#pytest-raises):
```
Note

When using pytest.raises as a context manager, itâ€™s worthwhile to note that normal context manager rules apply and that the exception raised must be the final line in the scope of the context manager. Lines of code after that, within the scope of the context manager will not be executed.
```

oh.

`AWSApp`'s "dispatcher" method was calling `exit()`s. This practically works,
but it was breaking tests by raising `SystemExit` before `capsys.readouterr()`
had a chance to capture output.  Substituting `exit()` for `return` will allow
`main.py` to handle dealing with the program's exit codes. 

Renaming the dipatcher method, `load_cli_args()`, to `run()` sounds more than
reasonable to me.

## aha
<https://docs.python.org/3/library/re.html#search-vs-match>
I have been using `match`, no wonder none of the regex's worked.

# ~~tomorrow~~ TODO

* more tests
* `destroy()` methods
* `getssh()`
* find other types of `ami`s
